### ISSUE TITLE
Replicator fails to run due to connection refused connecting to market data

### ISSUE THREAD

**Issue by zbroniszewski** [jvirtanen/genesis#6]
Running (. etc/example.sh; ./bin/genesis-replicator) fails: Error: connect ECONNREFUSED 127.0.0.1:5000. I've also opened up the same issue here: https://github.com/paritytrading/parity/issues/136

This is due to the system config only accepting MoldUDP64 settings, so NPM package soupbintcp cannot connect. There's not even really a reason to have SoupBINTCP example configurations for ticker and reporter applications if this is the case, right?

**Comment by jvirtanen** [comment]
Hi @zbron99! If you want to run the replicator locally, you need to run [Nassau SoupBinTCP Gateway](https://github.com/paritytrading/nassau/tree/master/applications/soupbintcp-gateway) in addition to the Parity Trading System. This provides the MoldUDP64 traffic generated by the trading system over SoupBinTCP. This is needed, because at the moment the replicator is not capable of connecting directly over MoldUDP64. I hope this helps! 🙂
